//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biblioteca
    {
        public int CodBli { get; set; }
        public string NomBli { get; set; }
        public Nullable<int> CodLibFK { get; set; }
        public Nullable<int> CodCliFK { get; set; }
        public Nullable<int> CodBibFK { get; set; }
        public Nullable<int> CodAdminFk { get; set; }
    
        public virtual Administrador Administrador { get; set; }
        public virtual Bibliotecario Bibliotecario { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
